[General]
filedialog-path=@Variant(\0\0\0\x11\0\0\0\x18\x66ile:///home/sd/.p/share)
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x5\xa3\0\0\x2\"\0\0\as\0\0\x4+\0\0\x2\xf6\0\0\x3\x1c\0\0\nu\0\0\a\x18\0\0\0\0\x2\0\0\0\a\x80\0\0\x5\xa6\0\0\x2%\0\0\ap\0\0\x4()

[FullScreen]
pos=@Point(560 1016)
screen=@Rect(0 0 1920 1080)
wide=false

[MainWindow]
adv-controls=0
bgSize=@Size(459 158)
pl-dock-status=true
playlist-visible=false
playlistSize=@Size(-1 -1)
status-bar-visible=false

[OpenDialog]
advanced=false
netMRL=
size=@Size(514 400)

[RecentsMRL]
list=file:///home/sd/share/moc/Mia%20Bangg%20Swallows%2010%20loads-ph57e802ac7c163.mp4, file:///home/sd/share/movie.mpg, file:///home/sd/.p/share/priv/jo2.mp4, file:///home/sd/.p/share/fav/Close-up%20cumshot%20-%20cum%20oozing%20from%20a%20black%20cock-ph5a9552ca726b6.mp4-00.00.22.836-00.00.46.576.mp4, directory:///home/sd/.p/share, file:///home/sd/.p/share/movie.mpg, file:///home/sd/2020-01-10%2011-26-57.mkv, file:///home/sd/2020-01-10%2011-25-16.mkv, file:///home/sd/share/me/2019-12-17%2012-55-39.mkv, file:///home/sd/share/fav/Close-up%20cumshot%20-%20cum%20oozing%20from%20a%20black%20cock-ph5a9552ca726b6.mp4-00.00.22.836-00.00.46.576.mp4, directory:///home/sd/share, file:///home/sd/share/moc/She%20Eats%20Cum%20from%2010%20Men%20-%20Pornhub.com.mp4-00.08.12.721-00.14.31.004.mp4, file:///home/sd/share/moc/fdssdf.mp4, file:///home/sd/Downloads/Cumslut%20Training-cumslut-training-405.mp4, file:///home/sd/share/Asian%20Solo%20Cumshot%20%7C%20XTube%20Porn%20Video%20from%20Red_Light_95.mp4, file:///home/sd/share/moc/JULES%20VAN%20SAINT%20swallows%208%20cumshots%20-%20Sperm%20Cocktail-ph581e1ef567ff0.mp4, file:///home/sd/share/moc/HEIDI%20swallows%2013%20loads%20-%20BrandonIron.com-ph591061960f9f7.mp4, file:///home/sd/share/moc/19yo%20cumslut%20swallows%209%20loads%20-%20BrandonIron.com-ph592c2f77e1fb0.mp4, file:///home/sd/share/.goutputstream-VNAED0, file:///home/sd/share/Close%20up%20cum-30380781.mp4, file:///home/sd/share/abundant%20sperm%20spurts-abundant-sperm-spurts.mp4
times=-1, -1, 0, 0, -1, 0, 0, 33780, 0, 0, 0, 0, 34284, 0, 0, 0, 0, 303956, 0, 26150, 0
