#! /bin/sh

sxhkd &
compton -b &
numlockx &
nitrogen --restore &
urxvtd -q -o -f
pamac-tray &
cbatticon &
blueberry-tray &
nm-applet &
volumeicon &
clipmenud &
~/.config/polybar/launch.sh &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          5

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true