[General]
activationHasRun=true
autoConfig=false
autoConfigServer=
autoHide=false
configFile=/home/sd/synergy.conf
cryptoEnabled=true
edition=0
elevateMode=false
elevateModeEnum=0
groupClientChecked=true
groupServerChecked=false
interface=
language=en
lastExpiringWarningTime=0
lastVersion=1.10.3-stable
logFilename=/home/sd/synergy.log
logLevel2=0
logToFile=false
minimizeToTray=false
port=24800
screenName=sdlap
serialKey=7B76313B62617369633B736861756E2064617669733B313B73646176697339323240676D61696C2E636F6D3B3B303B307D
serverHostname=
startedBefore=true
useExternalConfig=false
useInternalConfig=true
wizardLastRun=8
