[General]
CustomWindowGeometry=@Rect(12 77 1896 964)
MaximizeOnStartup=false
OpenFolder=
RecentFiles=@Variant(\0\0\0\t\0\0\0\x1\0\0\0\n\0\0\0\x32\0/\0h\0o\0m\0\x65\0/\0s\0\x64\0/\0m\0p\0v\0-\0s\0h\0o\0t\0\x30\0\x30\0\x30\0\x31\0.\0j\0p\0g)
SaveFolder=/home/sd
SaveFormat=
UserLanguage=notset
compressionDefaultEnabled=false
compressionDefaultValue=90
compressionDialogEnabled=true
dockLayout=0
historyLimit=24
memorizeParamsEnabled=true
prevOpened=false
prevOpenedSave=false
saveFormatEnabled=false
unit=0
zoomDirection=0
